---

- hosts: webserver
  become: true
  tasks:

  - name: Update repo & install apache2
    tags: webserver,apache,ubuntu
    apt:
      name: apache2
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: copy web html file
    tags: html,copy
    copy:
      src: default.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

  - name: Restart apache service
    tags: restart-apache
    ansible.builtin.service:
      name: apache2
      state: restarted

- hosts: workstation
  become: true
  tasks:

  - name: install unzip
    package:
      name: unzip

  - name: install terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/1.9.8/terraform_1.9.8_linux_amd64.zip
      dest: /usr/local/bin/
      remote_src: yes
      owner: root
      group: root
      mode: 0755
