---

- hosts: all
  become: true
  tasks:

  - name: update_repository
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install php
    yum:
      name: php
      state: latest
    when: ansible_distribution in ["CentOS"]

  - name: install apache2
    apt:
      name: apache2
      state: latest
    when: ansible_distribution in ["Ubuntu"]
