---

- hosts: all
  become: true
  tasks:

  - name: update_repository
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install php & apache package
    yum:
      name: 
        - php
        - httpd  
      state: latest
    when: ansible_distribution in ["CentOS"]

  - name: install apache2 & php package
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution in ["Ubuntu"]
